
# TravisCI virtualisation environment
# see: https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

sudo: false
dist: trusty

language: java

script:
 - ./gradlew assemble
 - ./gradlew check
 - ./gradlew build
 - ./gradlew fatJar
 - ./bin/generateHelpDocs.sh
 - ./bin/travis_ci_after_build_checks.sh

