
# TravisCI virtualisation environment
# see: https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

sudo: false
dist: trusty

language: java

env:
  - GRADLE_VERSION=3.4.1
  - GRADLE_VERSION=4.6

jdk:
  - oraclejdk8
  - openjdk8

install:
 - ./gradlew wrapper --gradle-version ${GRADLE_VERSION}
 - ./gradlew assemble

script:
 - ./gradlew check
 - ./gradlew build
 - ./gradlew executableJar
 - ./bin/generateHelpDocs.sh
 - ./bin/travis_ci_after_build_checks.sh

